modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="nextbots_smart"
version="2.0.0-beta"
displayName="NextBot's Smart - Advanced Horror Beta"
displayURL="https://github.com/Kjoe-cmyk/PinHead"
credits="Complete restoration with advanced behaviors and performance enhancements"
authors="NextBots Smart Team"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.nextbots_smart]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration